apiVersion: v1
kind: Pod
metadata:
  name: jenkins-restart-always
  labels:
    devops: "test"
spec: 
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts  
    ports:
    - containerPort: 8080
  restartPolicy: Always
