apiVersion: v1
kind: ReplicationController
metadata:
  name: devops-rc-example
spec: 
  replicas: 3
  selector:
    type: java
  template:
    metadata:
      name: jenkins
      labels:
        type: java
    spec: 
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts  
        ports:
        - containerPort: 8080
