apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-resource
spec:
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 200Mi
            cpu: 5M
          limits: 
            memory: 300Mi
            cpu: 100M
