apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-resource-1
spec:
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "1M"
          limits: 
            memory: "200Mi"
            cpu: "10M"
