apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-petclinic-2
spec:
  containers:
  - name: liveness
    image: malleshdevops/petclinic:spring-k8s
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60
#      periodSeconds: 20
    livenessProbe:
      httpGet:
        path: /
        port: 8080
#      initialDelaySeconds: 60
#      periodSeconds: 5
