apiVersion: v1
kind: Pod
metadata: 
  name: liveness-tcp-socket-fail
  labels:
    app: httpd-web
spec: 
  containers:
  - name: httpd
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 81
